name: ❓ Question
description: Ask a question about SoftScout PDF
title: "(Question) "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Your question here...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: What solutions have you already attempted?
      placeholder: Describe what you've tried so far...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant code snippets, screenshots, or scenarios.
    validations:
      required: false
